---
- name: Set JAVA_HOME variable in hadoop-env.sh file
  ansible.builtin.lineinfile:
    path: "{{ __hadoop_installation_dir }}/etc/hadoop/hadoop-env.sh"
    regexp: '^export JAVA_HOME='
    line: 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk'

- name: Define new properties to be added or updated in core-site.xml
  set_fact:
    new_properties:
      fs.defaultFS: "hdfs://{{ groups['master'][0] }}:9000"
      io.file.buffer.size: 131072

- name: Remove existing properties if they exist
  lineinfile:
    path: "{{ __hadoop_installation_dir }}/etc/hadoop/core-site.xml"
    regexp: '<property><name>{{ item.key }}</name>'
    state: absent
  loop: "{{ new_properties | dict2items }}"

- name: Add the new properties to core-site.xml
  lineinfile:
    path: "{{ __hadoop_installation_dir }}/etc/hadoop/core-site.xml"
    insertafter: '<configuration>'
    line: '  <property><name>{{ item.key }}</name><value>{{ item.value }}</value></property>'
  loop: "{{ new_properties | dict2items }}"