---
- name: Start HDFS NameNode
  command: "{{ __hadoop_installation_dir }}/bin/hdfs --daemon start namenode"
  when: "'namenode' in hostvars[inventory_hostname]"
  args:
    creates: /tmp/hadoop-hdfs-namenode.pid
  become: true
  become_user: hdfs
  become_method: su

- name: Start HDFS DataNode
  command: "{{ __hadoop_installation_dir }}/bin/hdfs --daemon start datanode"
  when: "'datanode' in hostvars[inventory_hostname]"
  args:
    creates: /tmp/hadoop-hdfs-datanode.pid
  become: true
  become_user: hdfs
  become_method: su

- name: Start YARN ResourceManager
  command: "{{ __hadoop_installation_dir }}/bin/yarn --daemon start resourcemanager"
  when: "'resourcemanager' in hostvars[inventory_hostname]"
  args:
    creates: /tmp/hadoop-yarn-resourcemanager.pid
  become: true
  become_user: yarn
  become_method: su

- name: Start YARN NodeManager
  command: "{{ __hadoop_installation_dir }}/bin/yarn --daemon start nodemanager"
  when: "'nodemanager' in hostvars[inventory_hostname]"
  args:
    creates: /tmp/hadoop-yarn-nodemanager.pid
  become: true
  become_user: yarn
  become_method: su